### ISSUE TITLE
[Feature Request] Option to disable sound

### ISSUE THREAD

**Issue by jake770321** [keyboardturner/Lorekeeper#3]
Hi, 
First of all, this addon is great and i wanted to thank you for making it.
Would it be possible to add an option to disable the sound you get when new ingame text is collected.
Thank you!

**Comment by keyboardturner** [comment]
can look into adding something for it soon

**Comment by keyboardturner** [comment]
latest version [0.1.2](https://github.com/keyboardturner/Lorekeeper/releases/tag/0.1.2) should now have option to disable sound
